version: "3"
services:
  rocket_code_service:
    container_name: ubuntu_rocket_code
    image: ubuntu:rocket_code
    build: .
    restart: on-failure
    volumes:
      - ${LOCATION}:/root/rocket_code    